module.exports = {
  Root: 'Root',
  Function: 'Function',
  Method: 'Method',
  Constructor: 'Constructor',
  For: 'For',
  ForIn: 'ForIn',
  Block: 'Block',
  Class: 'Class',
  THIS: 'this',
  EXPORTS: 'exports',
  MODULE: 'module',
  MODULE: 'module',
  EXPORTS: 'exports',
  REQUIRE: 'require',
  UNDEFINED: 'undefined',
  ARGUMENTS: 'arguments',
  NEW: 'new',
  ANONYMOUS: 'anonymous',
  Let:'let',
  Const:'const',
  Var:'var',
  If:"If",
  Object:'Object',
  ForChild:'ForChild',
  DoWhile:'DoWhile',
  While:'While',
  Try:'Try',
  Catch:'Catch',
  Finally:'Finally',
  Switch:'Switch',
}